services:
  php-apache:
    build: .
    container_name: php-apache-container
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - php_network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - php_network
    ports:
      - "3306:3306"

networks:
  php_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
