version: '3.9'

services:
  db_primary:
    image: postgres:latest
    container_name: db_primary
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: primarydb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - db_network
    volumes:
      - db_primary_data:/var/lib/postgresql/data
      - ./primary_pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./init_primary.sql:/docker-entrypoint-initdb.d/init_primary.sql
    command: ["postgres", "-c", "wal_level=logical", "-c", "max_replication_slots=10", "-c", "max_wal_senders=10"]

  db_replica:
    image: postgres:latest
    container_name: db_replica
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: replicadb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    networks:
      - db_network
    volumes:
      - db_replica_data:/var/lib/postgresql/data
      - ./init_replica.sql:/docker-entrypoint-initdb.d/init_replica.sql
    depends_on:
      - db_primary
    command: ["postgres", "-c", "hot_standby=on"]

networks:
  db_network:
    driver: bridge

volumes:
  db_primary_data:
  db_replica_data:
