services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine
    container_name: nfs-server
    privileged: true
    restart: always
    environment:
      - SHARED_DIRECTORY=/home/carpetacompartidaASO
    volumes:
      - nfs-data:/home/carpetacompartidaASO
    ports:
      - "2049:2049"

  nfs-client:
    image: ubuntu
    container_name: nfs-client
    privileged: true
    depends_on:
      - nfs-server
    command: >
      sh -c "apt update &&
             apt install -y nfs-common &&
             mkdir -p /mnt/nfs &&
             mount -o vers=4 nfs-server:/home/carpetacompartidaASO /mnt/nfs &&
             tail -f /dev/null"
    volumes:
      - nfs-data:/mnt/nfs

volumes:
  nfs-data:
    driver: local